# Don't spam me please, I'll check Travis manually.
notifications:
  email: false

sudo: false

language: rust

addons:
  apt:
    packages:
    - libasound2-dev

rust:
  - 1.4.0
  - 1.5.0
  - 1.6.0
  - 1.7.0
  - 1.8.0
  - 1.9.0
  - 1.10.0
  - 1.11.0
  - 1.12.0
  - 1.13.0
  - 1.14.0
  - 1.15.1
  - 1.16.0
  - beta
  - nightly

# Apart from the above Rust versions on Linux, also test on stable Rust on OS X.
matrix:
  include:
    - os: osx
      rust: stable
