# Don't spam me please, I'll check Travis manually.
notifications:
  email: false

sudo: false

language: rust

addons:
  apt:
    packages:
    - libasound2-dev

rust:
  # Test on every other Rust version since the minimum supported version, to not
  # waste too many resources.
  - 1.4.0
  - 1.6.0
  - 1.8.0
  - 1.10.0
  - 1.12.0
  - 1.14.0
  - 1.16.0
  - 1.18.0
  - beta
  - nightly

# Apart from the above Rust versions on Linux, also test on stable Rust on OS X.
matrix:
  include:
    - os: osx
      rust: stable
