[package]

name = "hound"
version = "2.0.0"
authors = ["Ruud van Asseldonk <dev@veniogames.com>"]
description = "A wav encoding and decoding library"
keywords = ["wav", "wave", "audio", "codec"]
license = "Apache-2.0"
readme = "readme.md"
homepage = "https://github.com/ruuda/hound"
repository = "https://github.com/ruuda/hound"
documentation = "https://ruuda.github.io/hound/doc/v2.0.0/hound/"

[dev-dependencies]
cpal = "0.1.2"

# TODO: enable this when sound_stream (or portaudio, actually) builds properly.
# sound_stream = "0.3.2"
