[package]

name = "hound"
version = "0.4.0"
authors = ["Ruud van Asseldonk <dev@veniogames.com>"]
description = "A WAV encoding and decoding library"
keywords = ["wav", "wave", "audio", "codec"]
license = "GPL-3.0"
readme = "readme.md"
homepage = "https://github.com/ruud-v-a/hound"
repository = "https://github.com/ruud-v-a/hound"
documentation = "https://ruud-v-a.github.io/hound/doc/v0.4.0/hound/"

[dev-dependencies]
cpal = "0.0.20"

# TODO: enable this when sound_stream (or portaudio, actually) builds properly.
# sound_stream = "0.3.2"
