[package]

name = "hound"
version = "0.1.0"
authors = ["Ruud van Asseldonk <dev@veniogames.com>"]
description = "A WAV encoding and decoding library"
keywords = ["wav", "wave", "audio", "codec"]
license = "GPL-3.0"
readme = "readme.md"
homepage = "https://github.com/ruud-v-a/hound"
repository = "https://github.com/ruud-v-a/hound"
